### ISSUE TITLE
Cordova doesn't build with this plugin installed

### ISSUE THREAD

**Issue by JohnMcLear** [randdusing/cordova-plugin-bluetoothle#2]
```
jose@mint ~/ble $ cordova run android
Generating config.xml from defaults for platform "android"
Preparing android project
Running app on platform "android" via command "/home/jose/ble/platforms/android/cordova/run" --device

/usr/local/lib/node_modules/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error: An error occurred while running the android project.
/home/jose/ble/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error executing "ant debug -f "/home/jose/ble/platforms/android/build.xml"": 
BUILD FAILED
/home/jose/Downloads/adt-bundle-linux-x86_64-20131030/sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/jose/Downloads/adt-bundle-linux-x86_64-20131030/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 3 seconds


    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cordova/src/run.js:67:22)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:730:16)
    at Process.ChildProcess._handle.onexit (child_process.js:797:5)
jose@mint ~/ble $ 
```

**Comment by jeremiehirsch** [comment]
Hello,

Can you tell me how you know the problem solved ?
I have the same problem :)

Thanks!

**Comment by randdusing** [comment]
The error output looks exactly the same? I don't see anything directly related to the Bluetooth plugin. Does the example app work for you?
