### ISSUE TITLE
Unfortunately, MyApp has stopped.

### ISSUE THREAD

**Issue by saudblaze** [randdusing/cordova-plugin-bluetoothle#502]
09-12 17:32:37.947 17584-17651/za.co.fusioncloud.jobapp E/chromium: [ERROR:budget_service.cc(145)] Unable to connect to the Mojo BudgetService.
09-12 17:34:01.099 17584-18046/za.co.fusioncloud.jobapp E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
                                                                          Process: za.co.fusioncloud.jobapp, PID: 17584
                                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzx;
                                                                              at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
                                                                              at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                              at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                              at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                              at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                              at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzx" on path: DexPathList[[zip file "/data/app/za.co.fusioncloud.jobapp-1/base.apk"],nativeLibraryDirectories=[/data/app/za.co.fusioncloud.jobapp-1/lib/arm, /vendor/lib, /system/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at com.google.android.gms.iid.zzd.zzeC(Unknown Source) 
                                                                              at com.google.android.gms.iid.zzd.<init>(Unknown Source) 
                                                                              at com.google.android.gms.iid.zzd.<init>(Unknown Source) 
                                                                              at com.google.android.gms.iid.InstanceID.zza(Unknown Source) 
                                                                              at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source) 
                                                                              at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
                                                                          	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.util.zzx
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                              		... 10 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by randdusing** [comment]
Nothing in the stack trace refers to the plugin, so it's unlikely an issue with this plugin.
