### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by askie** [randdusing/cordova-plugin-bluetoothle#514]
```
cordova --version
8.1.2 (cordova-lib@8.1.1)
```
error:
```
cordova plugin add cordova-plugin-bluetoothle --stacktrace --info
Installing "cordova-plugin-bluetoothle" for android
ANDROID_HOME=/Users/askie/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
Subproject Path: CordovaLib

> Configure project :
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_8e9imgo6830vo4yjpq3r4ndsn.run(/wwwroot/ionic3/dhfprinter1/platforms/android/build.gradle:145)

> Configure project :CordovaLib
publishNonDefault is deprecated and has no effect anymore. All variants are now published.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean'.
> Unable to delete file: /wwwroot/ionic3/dhfprinter1/platforms/android/build/generated/source/r/release/org/apache/cordova/R.java

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
Failed to install 'cordova-plugin-bluetoothle': Error: /wwwroot/ionic3/dhfprinter1/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/wwwroot/ionic3/dhfprinter1/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
/wwwroot/ionic3/dhfprinter1/platforms/android/gradlew: Command failed with exit code 1
```

**Comment by askie** [comment]
use sudo to install successfull!
